"""Fix server defaults and add SM2 fields

Revision ID: 47a1bce19bc9
Revises: 
Create Date: 2025-06-25 10:04:13.997579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a1bce19bc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quesans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('EasinessFactor', sa.Float(), server_default='2.5', nullable=False))
        batch_op.add_column(sa.Column('Repetitions', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('Interval', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('LastGrade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quesans', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('LastGrade')
        batch_op.drop_column('Interval')
        batch_op.drop_column('Repetitions')
        batch_op.drop_column('EasinessFactor')

    # ### end Alembic commands ###
